services:
  api:
    container_name: todolist
    image: node:20
    working_dir: /usr/src/todolist
    restart: always
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_HOST=my-postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=todolist
    volumes:
      - './package.json:/usr/src/todolist/package.json'
      - './package-lock.json:/usr/src/todolist/package-lock.json'
      - './dist:/usr/src/todolist/dist'
    ports:
      - "3000:3000"
    command: bash -c "npm install --omit=dev --force && npm run dev -- --exitcrash"
    networks:
      - todolist-network
networks:
  todolist-network:
    name: todolist-network
    external: true